version: 2
jobs:
  rspec:
    docker:
      - image: circleci/ruby:2.5.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Rspec
          command: bundle exec rspec spec/ --format documentation

workflows:
  version: 2
  workflows:
    jobs:
      - rspec: