version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby:2.5.7-node-browsers
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_USERNAME: 'root'
          DB_PASSWORD: ''
      - image: circleci/mysql:5.7

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: update bundler
          command: |
            gem update --system
            gem install bundler
      - run:
          name: bundle install
          command: bundle install --path vendor/bundle
      - run:
          name: データベースの起動を待機
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: データベースのセットアップ
          command: bundle exec rails db:schema:load
      - run:
          name: テストの実行
          command: bundle exec rspec


workflows:
  version: 2
  workflows:
    jobs:
      - test